services:
  # mysql:
  #   image: mysql:8.0
  #   container_name: mysql-db
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root_password
  #     MYSQL_DATABASE: test
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: password
  #   ports:
  #     - "3308:3306"
  #   networks:
  #     - scone_scone
  #   volumes:
  #     - db_data:/var/lib/mysql

  sql-proxy:
    image: oven/bun
    container_name: sql-proxy
    expose:
      - "3007"
    volumes:
      - .:/app
    command: bun run /app/index.ts
    networks:
      - scone_scone

volumes:
  db_data:
    driver: local

networks:
  scone_scone:
    external: true
